version: '3'

services:
###> doctrine/doctrine-bundle ###
  db:
    image: mariadb:latest
    platform: linux/x86_64
    container_name: db_hypnos
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db_hypnos
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev
    ports:
      - "3306:3306"
###< doctrine/doctrine-bundle ###

###> phpMyadmin ###
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_hypnos
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev
###< phpMyadmin ###

###> MailDev ###
  maildev:
    image: maildev/maildev
    container_name: maildev_docker_symfony
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: always
    networks:
      - dev
###< MailDev ###

networks:
  dev:

volumes:
  db-data: